version: "3.7"
services:
  fdb-coordinator:
    image: foundationdb/foundationdb:6.0.18
    environment:
      FDB_PORT: 4500
      FDB_NETWORKING_MODE: container
      FDB_COORDINATOR: fdb-coordinator
    volumes:
      - fdb-coordinator:/var/fdb/data
  fdb:
    image: foundationdb/foundationdb:6.0.18
    environment:
      FDB_PORT: 4500
      FDB_NETWORKING_MODE: container
      FDB_COORDINATOR: fdb-coordinator
    volumes:
      - fdb:/var/fdb/data
  fdb-document-layer:
    image: foundationdb/fdb-document-layer:1.7.1
    environment:
      FDB_DOC_PORT: 27016
      FDB_NETWORKING_MODE: container
      FDB_CLUSTER_FILE_CONTENTS: docker:docker@172.23.0.4:4500 
    ports:
      - "27016:27016"
volumes:
  fdb:
  fdb-coordinator:
